version: "3.8"

services:

  web:
    build:
      context: ./
    command: gunicorn stripe_api.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./project/.env
    
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
